config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do

      resources :districts, only: [] do
        collection do
          get :return_districts_by_city_id
        end
      end

      # resources :restaurants, only: [] do
      #   collection do
      #     get :find_restaurants_by_city
      #   end
      # end
      resources :posts, only: [] do
        member do
          post :like
        end

        collection do
          get :more_post
        end

      end
      resources :comments do
        member do
          post :create_reply_comment
          get :replies
          delete :destroy_reply
        end
      end

      resources :carts, only: [] do
        member do
          post :choose_food
          post :increase_quantity
          post :decrease_quantity
          post :cancel_food
          post :cart
        end
      end

      resources :notifications, only: [] do
        collection do
          get :check_notification
        end
      end
      # resources :reviews, only: [] do
      #   member do
      #     delete :destroy_review
      #   end
      # end

    end
  end

  namespace :admin do
    get 'restaurants/store_pendding', to: 'restaurants#store_pendding'
    resources :restaurants do
      collection do
        get :find_restaurant
      end
    end
    resources :users do
      collection do
        get :find_user
      end
    end
    resources :posts do
      collection do
        get :find_post
      end
    end
  end

  namespace :dashboard do
    get 'restaurants/store_pendding', to: 'restaurants#store_pendding'
    resources :restaurants do
      resources :foods do
        collection do
          get :find_food
        end
      end

      resources :staffs do
        collection do
          get :find_staff
        end
      end

      resources :orders, only: [] do
        collection do
          get :orders_pending
          get :orders_shipping
          get :orders_complete
          get :orders_cancel
        end


        member do
          patch :accept_order
          patch :complete_ship
          patch :cancel_order
        end
      end

    end

    resources :orders, only: [] do
      collection do
        get :orders_pending_user
        get :orders_shipping_user
        get :orders_complete_user
        get :orders_cancel_user
      end


      member do
        patch :cancel_order_user
      end
    end

    resources :posts do
      collection do
        get :find_post
      end
    end
  end

  resources :posts do
    collection do
      get :find_post
      get :contact
      post :create_contact
    end

  end
  # resources :comments
  resources :restaurants do

    resources :reviews
    member do
      get :show_foods_drinks
      get :new_cart
      post :cart

    end

    collection do
      get :find_restaurant
      get :find_restaurant_by_address
    end
  end
  resources :users do
    member do
      post :change_password
    end
  end


  get"/login" => "sessions#new", as: :login
  post"/sign" => "sessions#create"
  get"/logout" => "sessions#logout"
  # get "/api/v1/return_districts_by_city_id"  => "api/v1/districts#return_districts_by_city_id"
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :restaurant

  validates :restaurant_id, presence:true
  validates :kind, presence: true
  validates :name, presence: true
  validates :salary, presence: true
  validates :phone, presence:true
  validates :birthday, presence:true

end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :check_user

  def check_user
      redirect_to posts_path if @current_user.nil?
  end

end

app/controllers/dashboard/foods_controller.rb
class Dashboard::FoodsController < Dashboard::BaseController


before_action :find_restaurant
  def index
    @page = 1
    @foods_eat = @restaurant.foods.where(kind: "eat").paginate(:page => params[:page], :per_page => 5)
    @foods_drink = @restaurant.foods.where(kind: "drink").paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
    @foods_page = @foods_eat
    @foods_page = @foods_drink if @foods_drink.count > @foods_eat.count

  end

  def find_food
    @page = 1
    food_name = params[:food_name]
    @restaurants = Restaurant.find_by_id params[:id]
    @foods = @restaurant.foods.where("name like ?", "%#{food_name}%").paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?

    if @foods.first.nil?
      flash[:error] = "Không tìm thấy thực phẩm "
      redirect_to dashboard_restaurant_foods_path
    end
  end

  def new
    @food = Food.new
  end

  def create
    @food = @restaurant.foods.new food_params
    if @food.save
      flash[:success] = "Thêm thực phẩm thành công"
      redirect_to dashboard_restaurant_foods_path
    else
      flash[:error] = "Thêm thực phẩm thất bại"
      render :new
    end
  end

  def edit
    @food = Food.find_by_id params[:id ]
    @eat = ""
    @drink = ""
    @eat = "selected" if @food.kind == "eat"
    @drink = "selected" if @food.kind == "drink"

  end

  def update
    @food = Food.find_by_id params[:id ]
    if @food.update_attributes(food_params)
      flash[:success] = "Chỉnh sửa đồ ăn thành công"
      redirect_to dashboard_restaurant_foods_path
    else
      flash[:error] = "Chỉnh sửa đồ ăn thất bại"
      render :edit
    end
  end

  def destroy
    @food = Food.find_by_id params[:id ]
    if @food.destroy
      flash[:success] = "Xóa đồ ăn thành công"
      redirect_to dashboard_restaurant_foods_path
    else
      flash[:success] = "Xóa đồ ăn thất bại"
      redirect_to dashboard_restaurant_foods_path
    end
  end

  private

  def food_params
    params.require(:food).permit(:kind, :name, :price, :image )

  end
  def find_restaurant
    @restaurant = Restaurant.find_by_id params[:restaurant_id]
  end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < Dashboard::BaseController
  before_action :find_restaurant

  def orders_pending
    @page = 1
    @orders = Order.where('(actived = ? AND restaurant_id = ?)', 0, @restaurant.id).order('updated_at asc').paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end


  def accept_order
    @order = Order.find_by_id params[:id]
    redirect_to posts_path if @order.restaurant.user_id != @current_user.id
    if @order.update_attributes(actived: 1)
      flash[:success] = "Chấp nhận đơn hàng thành công chuyển sang giao hàng."
      redirect_to orders_shipping_dashboard_restaurant_orders_path
    else
      flash[:error] = "Chưa chấp nhận đơn hàng"
      render :orders_pending
    end
  end

  def orders_shipping
    @page = 1
    @orders = Order.where('(actived = ? AND restaurant_id = ?)', 1, @restaurant.id).paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def complete_ship
    @order = Order.find_by_id params[:id]
    redirect_to posts_path if @order.restaurant.user_id != @current_user.id
    if @order.update_attributes(actived: 2)
      flash[:success] = "Đơn hàng đã được hoàn tất."
      redirect_to orders_complete_dashboard_restaurant_orders_path
    else
      flash[:error] = "Đơn hàng chưa hoàn tất."
      render :orders_shipping
    end
  end

  def cancel_order
    @order = Order.find_by_id params[:id]
    redirect_to posts_path if @order.restaurant.user_id != @current_user.id
    if @order.update_attributes(actived: 3)
      flash[:success] = "Hủy đơn hàng thành công."
      redirect_to orders_cancel_dashboard_restaurant_orders_path
    else
      flash[:error] = "Đơn hàng chưa hoàn tất."
      render :orders_pending
    end
  end

  def orders_complete
    @page = 1
    @orders = Order.where('(actived = ? AND restaurant_id = ?)', 2, @restaurant.id).paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def orders_cancel
    @page = 1
    @orders = Order.where('(actived = ? AND restaurant_id = ?)', 3, @restaurant.id).paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end


  def orders_pending_user
    @page = 1
    @orders = Order.where('(actived = ? AND user_id = ?)', 0, @current_user.id).order('restaurant_id desc').paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def orders_shipping_user
    @page = 1
    @orders = Order.where('(actived = ? AND user_id = ?)', 1, @current_user.id).order('restaurant_id desc').paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def orders_complete_user
    @page = 1
    @orders = Order.where('(actived = ? AND user_id = ?)', 2, @current_user.id).order('restaurant_id desc').paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def cancel_order_user
    @order = Order.find_by_id params[:id]
    redirect_to posts_path if @order.user.id != @current_user.id
    if @order.update_attributes(actived: 3)
      flash[:success] = "Hủy đơn hàng thành công."
      redirect_to orders_cancel_user_dashboard_orders_path
    else
      flash[:error] = "Đơn hàng chưa hoàn tất."
      render :orders_pending
    end
  end

  def orders_cancel_user
    @page = 1
    @orders = Order.where('(actived = ? AND user_id = ?)', 3, @current_user.id).order('restaurant_id desc').paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end


  private

  def find_restaurant
    @restaurant = Restaurant.find_by_id params[:restaurant_id]
  end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < Dashboard::BaseController

  before_action :find_post_by_id, only: [:edit, :update, :destroy]
  def index
    @page = 1
    @posts = @current_user.posts.order('created_at desc').paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def find_post
    @page = 1
    title_name = params[:title_name]
    @posts = @current_user.posts.where("title like ? ", "%#{title_name}%").paginate(:page => params[:page], :per_page =>5)
    @page = params[:page].to_i if params[:page].present?
    if @posts.first.nil?
      flash[:error] = "Không tìm thấy bài đăng"
      redirect_to dashboard_posts_path
    end

  end

  def edit
    # redirect_to posts_path if @post.user_id != @current_user.id
    if !(@post.user_id == @current_user.id || @current_user.is_admin? )
      redirect_to dashboard_post_path
    end
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success]= "Bạn vừa sửa bài viết thành công"
      redirect_to dashboard_posts_path
    else
      render :edit
    end
  end


  def destroy
    # redirect_to posts_path if @post.user_id != @current_user.id
    if !(@post.user_id == @current_user.id || @current_user.is_admin? )
      redirect_to dashboard_posts_path
    end
    if @post.destroy
      flash[:success]= "Bạn vừa xóa bài viết thành công"
      redirect_to dashboard_posts_path
    else
      render :index
    end
  end

  private

  def check_user
      redirect_to login_path if @current_user.nil?
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post_by_id
    @post = Post.find_by_id params[:id]
  end

end

app/controllers/dashboard/restaurants_controller.rb
class Dashboard::RestaurantsController < Dashboard::BaseController

  def index
    @page = 1
    @restaurants = @current_user.restaurants.where(actived: 1).paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?

  end

  def store_pendding
    @page = 1
    @restaurants = @current_user.restaurants.where(actived: 0).paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def new
    @restaurant = @current_user.restaurants.new
    @cities = City.all
  end

  def create
    @cities = City.all
    @restaurant = @current_user.restaurants.new restaurant_params

    if @restaurant.save
      flash[:success] = "Tạo cửa hàng thành công"
      redirect_to dashboard_restaurants_path
    else
      # flash[:error] = "Tạo cửa hàng thất bại"
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant.user_id != @current_user.id
      redirect_to dashboard_restaurants_path
    end
    @cities = City.all
    @city = City.find_by_id @restaurant.district.city.id
    @districts = @city.districts
  end

  def update
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant.user_id != @current_user.id
      redirect_to dashboard_restaurants_path
    end
    if @restaurant.update_attributes(restaurant_params)
      flash[:success] = "Cập nhật cửa hàng #{@restaurant.name} thành công"
      redirect_to dashboard_restaurants_path
    else
      flash[:error] = "Cập nhật cửa hàng #{@restaurant.name} thất bại"
      render :edit
    end
  end
  def show
    @restaurant = Restaurant.find_by_id params[:id]
  end

  def destroy
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant.user_id != @current_user.id
      redirect_to dashboard_restaurants_path
    end
    if @restaurant.destroy
      flash[:success] = "Xóa cửa hàng thành công"
      redirect_to dashboard_restaurants_path
    else
      flash[:error] = "Xóa cửa hàng thất bại "
      redirect_to dashboard_restaurants_path
    end
  end
  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone, :district_id, :address, :image)

  end

end

app/controllers/dashboard/staffs_controller.rb
class Dashboard::StaffsController <  Dashboard::BaseController
  before_action :find_restaurant

  def index
    @page = 1
    @staffs = @restaurant.staffs.order('kind desc').paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def find_staff
    @page = 1
    staff_name = params[:staff_name]
    @restaurant = Restaurant.find_by_id params[:restaurant_id]
    @staffs = @restaurant.staffs.where("name like ?", "%#{staff_name}%").paginate(:page => params[:page], :per_page => 5)
    @page = params[:page].to_i if params[:page].present?

    if @staffs.first.nil?
      flash[:error] = "Không tìm thấy nhân viên"
      redirect_to dashboard_restaurant_staffs_path
    end
  end

  def new
    @staff = @restaurant.staffs.new
  end

  def create
    @staff = @restaurant.staffs.new staff_params
    if @staff.save
      flash[:success] = "Thêm nhân viên thành công"
      redirect_to dashboard_restaurant_staffs_path
    else
      # flash[:error] = "Thêm nhân viên thất bại"
      render :new
    end
  end

  def edit
    @staff = Staff.find_by_id params[:id]
    @male = false
    @female = false
    if @staff.gender == true
      @male = true
    else
      @female = true
    end
  end

  def update
    @staff = Staff.find_by_id params[:id]
    if @staff.update_attributes(staff_params)
      flash[:success] = "Chỉnh sửa nhân viên thành công"
      redirect_to dashboard_restaurant_staffs_path
    else
      flash[:error] = "Chỉnh sửa nhân viên thất bại"
      render :edit
    end
  end

  def destroy
    @staff = Staff.find_by_id params[:id]
    if @staff.destroy
      flash[:success] = "Xóa nhân viên thành công"
      redirect_to dashboard_restaurant_staffs_path
    else
      flash[:error] = "Xóa nhân viên thất bại"
      render :edit
    end
  end
  private

  def staff_params
    params.require(:staff).permit(:kind, :name, :salary, :phone, :birthday, :gender)
  end
  def find_restaurant
    @restaurant = Restaurant.find_by_id params[:restaurant_id]
  end
end

app/views/dashboard/staffs/edit.html.erb
<% if @staff.errors.any? %>
  <div class="col-md-12 alert alert-danger">
    <% @staff.errors.full_messages.each do |message| %>
      <li><%= message%></li>
    <%end%>
  </div>
<% end %>

<div class="container">
  <h1 class="text-center text-danger">Sửa nhân viên</h1>
  <fieldtest>
  <%= form_for :staff, url: dashboard_restaurant_staff_path , method: "patch" do |f| %>
    <div class="col-md-4 col-sm-offset-4">
      <div class="form-group">
        <label for="">Chức vụ</label>
        <select class="form-control" name="staff[kind]">
          <option value="Quản lý">Quản lý</option>
          <option value="Kế toán">Kế toán</option>
          <option value="Lễ tân">Lễ tân</option>
          <option value="Đầu bếp">Đầu bếp</option>
          <option value="Bồi bàn">Bồi bàn</option>
          <option value="Bảo vệ">Bảo vệ</option>
        </select>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Tên</label>
        <%= f.text_field :name, class: "form-control", placeholder: "Tên" , required: "required"%>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Lương</label>
        <%= f.text_field :salary, class: "form-control", placeholder: "Lương" , required: "required"%>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Số điện thoại</label>
        <%= f.text_field :phone, class: "form-control", placeholder: "Số điện thoại", required: "required" %>
      </div>

      <div class="form-group">
        <label for="example-date-input" class="col-2 col-form-label">Ngày sinh</label>
        <%= f.text_field :birthday, class: "form-control datepicker", placeholder: "Ngày sinh", required: "required"%>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Giới tính:</label>
        <%= f.radio_button :gender, '1', :checked => @male %> Nam
        <%= f.radio_button :gender, '0',:checked => @female %> Nữ
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-primary text-center " name="button">Sửa</button>
        <a href="<%= dashboard_restaurant_staffs_path%>" class="btn btn-danger magin_left_10">Hủy</a>
      </div>

      <%end%>
      </fieldtest>
    </div>
  </div>

app/views/dashboard/staffs/find_staff.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%=dashboard_restaurants_path%>">Quản lý cửa hàng<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
        <li ><a href="<%=dashboard_restaurant_foods_path%>">Quản lý món ăn<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-glass"></span></a></li>
        <li ><a href="<%=dashboard_restaurant_staffs_path%>">Quản lý nhân viên<span style="font-size:16px;" class="pull-right hidden-xs showopacity  glyphicon glyphicon-user"></span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quản lý đặt hàng<span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity 	glyphicon glyphicon-shopping-cart"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="<%=orders_pending_dashboard_restaurant_orders_path(@restaurant)%>">Đơn hàng chờ duyệt</a></li>
            <li><a href="<%=orders_shipping_dashboard_restaurant_orders_path(@restaurant)%>">Đơn hàng chờ giao</a></li>
            <li><a href="<%=orders_complete_dashboard_restaurant_orders_path(@restaurant)%>">Đơn hàng đã giao</a></li>
            <li><a href="<%=orders_cancel_dashboard_restaurant_orders_path(@restaurant)%>">Đơn hàng đã hủy</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <div class="container">

    <!-- <div class="btn-group">
      <a class="btn btn-default" href="<%=dashboard_restaurants_path%>">Quản lý cửa hàng</a>
      <a class="btn  btn-default" href="<%=dashboard_restaurant_foods_path%>">Quản lý món ăn</a>
      <a href="" class="btn btn-info">Quản lý nhân viên</a>
      <a href="#" class="btn btn-default">Quản lý đặt hàng</a>
    </div> -->
    <div class="row">
      <div class="col-md-12 row">
        <div class="margin_top_10 form-group col-md-4 row">
          <form class="navbar-form" role="search" action="/dashboard/restaurants/<%=@restaurant.id%>/staffs/find_staff" method="get">
          <div class="input-group">
              <input type="text" class="form-control" placeholder="Tên nhân viên..." name="staff_name">
              <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">  <i class="glyphicon glyphicon-search"></i></button>
              </div>
          </div>
          </form>
        </div>
      </div>
    </div>
    <h1 class="text-center text-danger margin_bottom_50 ">Nhân viên tương ứng <%=@restaurant.name %></h1>
    <div class=" margin_bottom_10">  <a href="<%=new_dashboard_restaurant_staff_path%>" class="btn btn-primary">Thêm nhân viên</a></div>




    <table class="table table-hover table-bordered" >
      <tr style="background: pink">
        <th>STT</th>
        <th>Tên nhân viên</th>
        <th>Chức vụ</th>
        <th>Lương</th>
        <th>Số điện thoại</th>
        <th>Ngày sinh</th>
        <th>Giớitính</th>
        <th>Ngày tạo</th>
        <th>Chức năng</th>
      </tr>
      <% @staffs.each_with_index do |staff,index| %>
      <tr class="box-foods">
        <td><%= index + 1 + (@page-1)*3  %></td>
        <td><%= staff.name %></td>
        <td><%= staff.kind %></td>
        <td><%= staff.salary %></td>
        <td><%= staff.phone %></td>
        <td><%= staff.birthday.strftime("%d/%m/%Y") %></td>
        <td>
          <%if staff.gender == true %>
            Nam
          <%else%>
            Nữ
          <%end%>
        </td>
        <td><%= staff.created_at.strftime("%H:%M %d/%m/%Y") %></td>
        <td>
          <a href="<%= edit_dashboard_restaurant_staff_path(staff.restaurant.id, staff.id ) %>" class="btn btn-warning">Sửa</a>
          <a href ="<%= dashboard_restaurant_staff_path(staff.restaurant.id, staff.id) %>" data-method="delete"  class="btn btn-danger delete-food" data-confirm="Bạn chắc chắn muốn xóa?">Xóa</a>
        </td>
      </tr>

      <% end %>
    </table>

    <div class="col-md-12">

      <div class="pagination pull-right">
        <%= will_paginate @staff , renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>

app/views/dashboard/staffs/index.html.erb
  <div class="container">

    <div class="btn-group">
      <a class="btn btn-default" href="<%=dashboard_restaurants_path%>">Quản lý cửa hàng</a>
      <a class="btn  btn-default" href="<%=dashboard_restaurant_foods_path%>">Quản lý món ăn</a>
      <a href="" class="btn btn-info">Quản lý nhân viên</a>
      <a href="#" class="btn btn-default">Quản lý đặt hàng</a>
    </div>
    <div class="row">
      <div class="col-md-12 row">
        <div class="margin_top_10 form-group col-md-4 row">
          <form class="navbar-form" role="search" action="/dashboard/restaurants/<%=@restaurant.id%>/staffs/find_staff" method="get">
          <div class="input-group">
              <input type="text" class="form-control" placeholder="Tên nhân viên..." name="staff_name">
              <div class="input-group-btn">
                <!-- <i class="glyphicon glyphicon-search"></i> -->
                  <button class="btn btn-default" type="submit">Tìm</button>
              </div>
          </div>
          </form>
        </div>
      </div>
    </div>
    <h1 class="text-center text-danger margin_bottom_50 ">Danh sách nhân viên <%=@restaurant.name %></h1>
    <div class=" margin_bottom_10">  <a href="<%=new_dashboard_restaurant_staff_path%>" class="btn btn-primary">Thêm nhân viên</a></div>




    <table class="table table-hover table-bordered" >
      <tr style="background: pink">
        <th>STT</th>
        <th>Tên nhân viên</th>
        <th>Chức vụ</th>
        <th>Lương</th>
        <th>Số điện thoại</th>
        <th>Ngày sinh</th>
        <th>Giớitính</th>
        <th>Ngày tạo</th>
        <th>Chức năng</th>
      </tr>
      <% @staffs.each_with_index do |staff,index| %>
      <tr class="box-foods">
        <td><%= index + 1 + (@page-1)*3  %></td>
        <td><%= staff.name %></td>
        <td><%= staff.kind %></td>
        <td><%= staff.salary %></td>
        <td><%= staff.phone %></td>
        <td><%= staff.birthday.strftime("%d/%m/%Y") %></td>
        <td>
          <%if staff.gender == true %>
            Nam
          <%else%>
            Nữ
          <%end%>
        </td>
        <td><%= staff.created_at.strftime("%H:%M %d/%m/%Y") %></td>
        <td>
          <a href="<%= edit_dashboard_restaurant_staff_path(staff.restaurant.id, staff.id ) %>" class="btn btn-warning">Sửa</a>
          <a href ="<%= dashboard_restaurant_staff_path(staff.restaurant.id, staff.id) %>" data-method="delete"  class="btn btn-danger delete-food" data-confirm="Bạn chắc chắn muốn xóa?">Xóa</a>
        </td>
      </tr>

      <% end %>
    </table>

    <div class="col-md-12">

      <div class="pagination pull-right">
        <%= will_paginate @staff , renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>

app/views/dashboard/staffs/new.html.erb
<% if @staff.errors.any? %>
  <div class="col-md-12 alert alert-danger">
    <% @staff.errors.full_messages.each do |message| %>
      <li><%= message%></li>
    <%end%>
  </div>
<% end %>

<div class="container">
  <h1 class="text-center text-danger">Thêm nhân viên</h1>
  <fieldtest>
  <%= form_for :staff, url: dashboard_restaurant_staffs_path , method: "post" do |f| %>
    <div class="col-md-4 col-sm-offset-4">
      <div class="form-group">
        <label for="">Chức vụ</label>
        <select class="form-control" name="staff[kind]">
          <option value="Quản lý">Quản lý</option>
          <option value="Kế toán">Kế toán</option>
          <option value="Lễ tân">Lễ tân</option>
          <option value="Đầu bếp">Đầu bếp</option>
          <option value="Bồi bàn">Bồi bàn</option>
          <option value="Bảo vệ">Bảo vệ</option>
        </select>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Tên</label>
        <%= f.text_field :name, class: "form-control", placeholder: "Tên" , required: "required"%>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Lương</label>
        <%= f.text_field :salary, class: "form-control", placeholder: "Lương" , required: "required"%>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Số điện thoại</label>
        <%= f.text_field :phone, class: "form-control", placeholder: "Số điện thoại", required: "required" %>
      </div>

      <div class="form-group">
        <label for="example-date-input" class="col-2 col-form-label">Ngày sinh</label>
        <%= f.text_field :birthday, class: "form-control datepicker", placeholder: "Ngày sinh", required: "required"%>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Giới tính:</label>
        <%= f.radio_button :gender, '1', :checked => true %> Nam
        <%= f.radio_button :gender, '0' %> Nữ
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-primary text-center " name="button">Thêm</button>
        <a href="<%= dashboard_restaurant_staffs_path%>" class="btn btn-danger magin_left_10">Hủy</a>
      </div>

      <%end%>
      </fieldtest>
    </div>
  </div>