config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do

      resources :districts, only: [] do
        collection do
          get :return_districts_by_city_id
        end
      end

      # resources :restaurants, only: [] do
      #   collection do
      #     get :find_restaurants_by_city
      #   end
      # end
      resources :posts, only: [] do
        member do
          post :like
        end

        collection do
          get :more_post
        end

      end
      resources :comments do
        member do
          post :create_reply_comment
          get :replies
          delete :destroy_reply
        end
      end

      resources :carts, only: [] do
        member do
          post :choose_food
          post :increase_quantity
          post :decrease_quantity
          post :cancel_food
          post :cart
        end
      end

      resources :notifications, only: [] do
        collection do
          get :check_notification
        end
      end
      # resources :reviews, only: [] do
      #   member do
      #     delete :destroy_review
      #   end
      # end

    end
  end

  namespace :admin do
    get 'restaurants/store_pendding', to: 'restaurants#store_pendding'
    resources :restaurants do
      collection do
        get :find_restaurant
      end
    end
    resources :users do
      collection do
        get :find_user
      end
    end
    resources :posts do
      collection do
        get :find_post
      end
    end
  end

  namespace :dashboard do
    get 'restaurants/store_pendding', to: 'restaurants#store_pendding'
    resources :restaurants do
      resources :foods do
        collection do
          get :find_food
        end
      end

      resources :staffs do
        collection do
          get :find_staff
        end
      end

      resources :orders, only: [] do
        collection do
          get :orders_pending
          get :orders_shipping
          get :orders_complete
          get :orders_cancel
        end


        member do
          patch :accept_order
          patch :complete_ship
          patch :cancel_order
        end
      end

    end

    resources :orders, only: [] do
      collection do
        get :orders_pending_user
        get :orders_shipping_user
        get :orders_complete_user
        get :orders_cancel_user
      end


      member do
        patch :cancel_order_user
      end
    end

    resources :posts do
      collection do
        get :find_post
      end
    end
  end

  resources :posts do
    collection do
      get :find_post
      get :contact
      post :create_contact
    end

  end
  # resources :comments
  resources :restaurants do

    resources :reviews
    member do
      get :show_foods_drinks
      get :new_cart
      post :cart

    end

    collection do
      get :find_restaurant
      get :find_restaurant_by_address
    end
  end
  resources :users do
    member do
      post :change_password
    end
  end


  get"/login" => "sessions#new", as: :login
  post"/sign" => "sessions#create"
  get"/logout" => "sessions#logout"
  # get "/api/v1/return_districts_by_city_id"  => "api/v1/districts#return_districts_by_city_id"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true
  validates :district_id, presence:true
  validates :user_id, presence: true


  has_attached_file :image, styles: { small: "64x64", med: "100x100", medium: "320x480",big:"640x800" , large: "1024x1900" },
    :default_url => "/images/restaurants/default_restaurant.jpg"
validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  belongs_to :user
  belongs_to :district
  has_many :foods, dependent: :delete_all
  has_many :staffs
  has_many :orders
  has_many :reviews

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  def index
    @page = 1
    @restaurants = Restaurant.order('created_at desc').where(actived: 1).paginate(:page => params[:page], :per_page => 10)
    @page =  params[:page].to_i if params[:page].present?
  end

  def store_pendding
    @page = 1
    @restaurants = Restaurant.order('created_at desc').where(actived: 0).all.paginate(:page => params[:page], :per_page => 10)
    @page =  params[:page].to_i if params[:page].present?
  end

  def find_restaurant
    @page = 1
    restaurant_name = params[:restaurant_name]
    result = Restaurant.where(:actived => 1)
    @restaurants = result.where("name like ?", "%#{restaurant_name}%").paginate(:page => params[:page], :per_page => 10)
    @page =  params[:page].to_i if params[:page].present?

    if @restaurants.first.nil?
      flash[:error] = "Không tìm thấy cửa hàng "
      redirect_to admin_restaurants_path
    end
  end

  def show
    @restaurant = Restaurant.find_by_id params[:id]
  end

  def update
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant.update_attributes(actived: 1)
      @restaurant.user.update_attributes(role: 1)
      flash[:success] = "Bạn đã duyệt cho cửa hàng #{@restaurant.name} thành công"
      redirect_to admin_restaurants_path
    else
      flash[:success] = "Bạn đã duyệt cho cửa hàng #{@restaurant.name} thất bại"
      redirect_to admin_restaurants_store_pendding_path
    end
  end

  def destroy
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant.destroy
      flash[:success] = "Đã xóa cửa hàng thành công"
      redirect_to admin_restaurants_store_pendding_path
    else
      flash[:error] = "Xóa cửa hàng thất bại"
      redirect_to admin_restaurants_store_pendding_path
    end
  end

end

app/controllers/api/v1/restaurants_controller.rb
module Api::V1
  class RestaurantsController < ApiController

    def find_restaurants_by_city
      if params[:city_id] != 1000
        @districts = District.where city_id: params[:city_id]
        @cities = City.all
        @page = 1
        @restaurants = @districts.first.restaurants.where(actived: true).paginate(:page => params[:page], :per_page => 9)
        @page = params[:page].to_i if params[:page].present?
        html = render_to_string(show: '/api/v1/restaurants/find_restaurants_by_city.html.erb')
        render json: {
          data: html
        }
      else
        @cities = City.all
        @page = 1
        @restaurants = Restaurant.where(actived: true).paginate(:page => params[:page], :per_page => 9)
        @page = params[:page].to_i if params[:page].present?
        html = render_to_string(show: '/restaurants/index.html.erb')
        render json: {
          data: html
        }
      end
    end
  end
end

app/controllers/dashboard/restaurants_controller.rb
class Dashboard::RestaurantsController < Dashboard::BaseController

  def index
    @page = 1
    @restaurants = @current_user.restaurants.where(actived: 1).paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?

  end

  def store_pendding
    @page = 1
    @restaurants = @current_user.restaurants.where(actived: 0).paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def new
    @restaurant = @current_user.restaurants.new
    @cities = City.all
  end

  def create
    @cities = City.all
    @restaurant = @current_user.restaurants.new restaurant_params

    if @restaurant.save
      flash[:success] = "Tạo cửa hàng thành công"
      redirect_to dashboard_restaurants_path
    else
      # flash[:error] = "Tạo cửa hàng thất bại"
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant.user_id != @current_user.id
      redirect_to dashboard_restaurants_path
    end
    @cities = City.all
    @city = City.find_by_id @restaurant.district.city.id
    @districts = @city.districts
  end

  def update
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant.user_id != @current_user.id
      redirect_to dashboard_restaurants_path
    end
    if @restaurant.update_attributes(restaurant_params)
      flash[:success] = "Cập nhật cửa hàng #{@restaurant.name} thành công"
      redirect_to dashboard_restaurants_path
    else
      flash[:error] = "Cập nhật cửa hàng #{@restaurant.name} thất bại"
      render :edit
    end
  end
  def show
    @restaurant = Restaurant.find_by_id params[:id]
  end

  def destroy
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant.user_id != @current_user.id
      redirect_to dashboard_restaurants_path
    end
    if @restaurant.destroy
      flash[:success] = "Xóa cửa hàng thành công"
      redirect_to dashboard_restaurants_path
    else
      flash[:error] = "Xóa cửa hàng thất bại "
      redirect_to dashboard_restaurants_path
    end
  end
  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone, :district_id, :address, :image)

  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


  def index
    @cities = City.all
    @page = 1
    @restaurants = Restaurant.where(actived: true).paginate(:page => params[:page], :per_page => 9)
    @page = params[:page].to_i if params[:page].present?
  end

  def find_restaurant
    @cities = City.all
    @page = 1
    restaurant_name = params[:restaurant_name]
    result = Restaurant.where(:actived => 1)
    @restaurants = result.where("name like ?", "%#{restaurant_name}%").paginate(:page => params[:page], :per_page => 9)
    @page = params[:page].to_i if params[:page].present?
    if @restaurants.first.nil?
      flash[:error] = "Không tìm thấy nhà hàng "
      redirect_to restaurants_path
    end
  end

  def find_restaurant_by_address
    @arrange = params[:arrange]
    if params[:city].blank?
      @address = false
      @cities = City.all
      if params[:arrange].blank?
        @restaurants = Restaurant.where(:actived => 1).paginate(:page => params[:page], :per_page => 9)
      else
        if params[:arrange] == "rating"
          @restaurants = Restaurant.where(:actived => 1).order(@arrange + ' desc').paginate(:page => params[:page], :per_page => 9)
        else
          @restaurants = Restaurant.where(:actived => 1).order(@arrange + ' desc').paginate(:page => params[:page], :per_page => 9)
        end
      end

    else
      @address = true
      return redirect_to restaurants_path if params[:city] == "city"
      @cities = City.all
      @city = City.find_by_id params[:city]
      @districts = @city.districts
      @district = 0

      @page = 1
      if params[:district].blank?
        if @arrange.blank?
          @restaurants = @city.restaurants.where(:actived => 1).paginate(:page => params[:page], :per_page => 9)
        else
          @restaurants = @city.restaurants.where(:actived => 1).order(@arrange + ' desc').paginate(:page => params[:page], :per_page => 9)
        end

      else
        @district = District.find_by_id params[:district]
        if @arrange.blank?
          @restaurants = @district.restaurants.where(:actived => 1).paginate(:page => params[:page], :per_page => 9)
        else
          @restaurants = @district.restaurants.where(:actived => 1).order(@arrange + ' desc').paginate(:page => params[:page], :per_page => 9)
        end

      end
      @page = params[:page].to_i if params[:page].present?
    end

  end

  def show
    @restaurant = Restaurant.find_by_id params[:id]
    @foods = @restaurant.foods.order('kind desc').paginate(:page => params[:page], :per_page => 9)
    session[:cart][@restaurant.id] = [] if session[:cart][@restaurant.id].nil?
    @total = 10000
    session[:cart][@restaurant.id].each do |f|
      @total += (f['quantity'] * f['price'] )
    end
    @reviews = @restaurant.reviews.order("created_at asc")
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new_cart
    redirect_to login_path if !@current_user
    @restaurant = Restaurant.find_by_id params[:id]
    @total = 10000
    session[:cart][@restaurant.id].each do |f|
      @total +=  f["quantity"] * f["price"]
    end

    # session[:cart][@restaurant.id].each do |f|
    #   @total += (f['quantity'] * f['price'] )
    # end
    # if @total = 10000
    #   flash[:error] = "Bạn chưa chọn món vào giỏ hàng"
    #   redirect_to restaurant_path(@restaurant)
    # end
  end

  def cart
    redirect_to login_path if !@current_user
    total = 10000
    @restaurant = Restaurant.find_by_id params[:id]
    @order = Order.new(user_id: @current_user.id, restaurant_id: @restaurant.id,phone: params[:phone], address: params[:address])
    if @order.save
      session[:cart][@restaurant.id].each do |f|
        @foods_of_order = FoodsOfOrder.new(order_id: @order.id, food_id: f["id"], quantity: f["quantity"], price: f["price"])
        if @foods_of_order.save
          total += (f["quantity"] * f["price"])
          next
        else
          @order.destroy
          break
          flash[:error] = "Đặt hàng thất bại"
          redirect_to restaurant_path(@restaurant)
        end
      end
      @order.update_attributes(total: total)
      flash[:success] = "Đặt hàng thành công"
      redirect_to restaurant_path(@restaurant)
    else
      flash[:error] = "Đặt hàng thất bại"
      redirect_to restaurant_path(@restaurant)
    end
  end


  # def find_restaurant
  #   @page = 1
  #   restaurant_name = params[:restaurant_name]
  #   result = Restaurant.where(:actived => 1)
  #   @restaurants = result.where("name like ?", "%#{restaurant_name}%").paginate(:page => params[:page], :per_page => 3)
  #   @page =  params[:page].to_i if params[:page].present?
  #
  #   if @restaurants.first.nil?
  #     flash[:error] = "Không tìm thấy cửa hàng "
  #     redirect_to admin_restaurants_path
  #   end
  # end

  def show_foods_drinks
    @restaurant = Restaurant.find_by_id params[:id]
    @foods = @restaurant.foods.where(kind: "drink").paginate(:page => params[:page], :per_page => 4)
  end


end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/find_restaurant.html.erb
  <div class="container">
    <div class="row">
      <div class="btn-group col-md-12">
        <a class="btn btn-info" href="">Quản lý cửa hàng</a>
        <a href="<%=admin_restaurants_store_pendding_path%>" class="btn btn-default">Cửa hàng chờ duyệt</a>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="margin_top_10 form-group col-md-6 row">
            <form class="navbar-form" role="search" action="/admin/restaurants/find_restaurant" method="get">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Tên nhà hàng..." name="restaurant_name">
                <div class="input-group-btn">            
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>




    <h1 class="text-center text-danger margin_bottom_50">Danh sách cửa hàng tương ứng</h1>
    <!-- <a href="<%= new_dashboard_restaurant_path%>" class = " btn btn-primary margin_bottom_10">Tạo cửa hàng</a> -->

    <table class="table table-hover table-bordered" >
      <tr style="background: pink">
        <th>STT</th>
        <th>Tên cửa hàng</th>
        <th>Số điện thoại</th>
        <th>Địa chỉ</th>
        <th>Ngày tạo</th>
        <th>Chức năng</th>
      </tr>
      <% @restaurants.each_with_index do |restaurant,index| %>
      <tr class="box-restaurants">
        <td><%= index + 1 + (@page-1)*3  %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.address %>, <%= restaurant.district.name %>, <%=restaurant.district.city.name%></td>
        <td><%= restaurant.created_at.strftime("%H:%M %d/%m/%Y") %></td>
        <td>
            <a href="<%= admin_restaurant_path(restaurant) %>"  class="btn btn-primary">Xem</a>
          <!-- <a href="<%= edit_dashboard_restaurant_path(restaurant) %>"  class="btn btn-warning">Sửa</a> -->
          <a href ="<%= dashboard_restaurant_path(restaurant) %>" data-method="delete" data-target="<%= restaurant.id %>" class="btn btn-danger delete-restaurant" data-confirm="Bạn chắc chắn muốn xóa?">Xóa</a>
        </td>
      </tr>

      <% end %>
    </table>
    <div class="pagination pull-right">
      <%= will_paginate @restaurants , renderer: BootstrapPagination::Rails %>
    </div>



  </div>

app/views/admin/restaurants/index.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%=admin_restaurants_path%>">Quản lý cửa hàng<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
        <li ><a href="<%=admin_restaurants_store_pendding_path%>">Cửa hàng chờ duyệt<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-hourglass"></span></a></li>

      </ul>
    </div>
  </div>
</nav>

  <div class="container">
    <div class="row">
      <!-- <div class="btn-group col-md-12">
        <a class="btn btn-info" href="">Quản lý cửa hàng</a>
        <a href="<%=admin_restaurants_store_pendding_path%>" class="btn btn-default">Cửa hàng chờ duyệt</a>
      </div> -->



    <div class="row">
      <div class="col-md-12">
        <div class="margin_top_10 form-group col-md-6 row">
          <form class="navbar-form" role="search" action="/admin/restaurants/find_restaurant" method="get">
          <div class="input-group">
              <input type="text" class="form-control" placeholder="Tên nhà hàng..." name="restaurant_name">
              <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>


    <h1 class="text-center text-danger margin_bottom_50">Danh sách cửa hàng của bạn</h1>
    <!-- <a href="<%= new_dashboard_restaurant_path%>" class = " btn btn-primary margin_bottom_10">Tạo cửa hàng</a> -->

    <table class="table table-hover table-bordered" >
      <tr style="background: pink">
        <th>STT</th>
        <th>Tên cửa hàng</th>
        <th>Số điện thoại</th>
        <th>Địa chỉ</th>
        <th>Ngày tạo</th>
        <th>Chức năng</th>
      </tr>
      <% @restaurants.each_with_index do |restaurant,index| %>
      <tr class="box-restaurants">
        <td><%= index + 1 + (@page-1)*3  %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.address %>, <%= restaurant.district.name %>, <%=restaurant.district.city.name%></td>
        <td><%= restaurant.created_at.strftime("%H:%M %d/%m/%Y") %></td>
        <td>
            <a href="<%= admin_restaurant_path(restaurant) %>"  class="btn btn-primary">Xem</a>
          <!-- <a href="<%= edit_dashboard_restaurant_path(restaurant) %>"  class="btn btn-warning">Sửa</a> -->
          <a href ="<%= admin_restaurant_path(restaurant) %>" data-method="delete" data-target="<%= restaurant.id %>" class="btn btn-danger delete-restaurant" data-confirm="Bạn chắc chắn muốn xóa?">Xóa</a>
        </td>
      </tr>

      <% end %>
    </table>
    <div class="pagination pull-right">
      <%= will_paginate @restaurants , renderer: BootstrapPagination::Rails %>
    </div>



  </div>

app/views/admin/restaurants/show.html.erb
  <div class="container"><a href="<%=admin_restaurants_path%>" class="btn btn-primary margin_top_10">Quay lại</a></div>
<h1 class="text-center text-danger margin_bottom_20 "><%=@restaurant.name %></h1>
  <div class="container">

    <div class="col-md-6">
      <%= image_tag @restaurant.image.url(:medium), class: "picture_center" %>
      <div  class="text-center big-star margin_top_10"><span class="star-rating" data-score="<%= @restaurant.rating%>">  </span><i class="text-muted"> <%=  @restaurant.reviews.length%>  đánh giá</i></div>
      <h3 class="text-center">Số điện thoại: <%=@restaurant.phone%></h3>
      <h3 class="text-center">Địa chỉ: <%=@restaurant.address%>, <%=@restaurant.district.name%>, <%=@restaurant.district.city.name%></h3>

    </div>
    <div class="col-md-6">
      <div id="map"></div>
    </div>

  </div>


     <script type="text/javascript">
       function initMap() {
         var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 16,
        // center: {lat: 16.0744633, lng: 108.1518328 }
         });
         var geocoder = new google.maps.Geocoder();
         geocodeAddress(geocoder, map);
       }
         function geocodeAddress(geocoder, resultsMap) {
           var address = "<%= @restaurant.address %>, <%= @restaurant.district.name %>, <%=@restaurant.district.city.name%>";
           geocoder.geocode({'address': address}, function(results, status) {
             if (status === 'OK') {
               resultsMap.setCenter(results[0].geometry.location);
               var marker = new google.maps.Marker({
                 map: resultsMap,
                 position: results[0].geometry.location
               });
             }
            //   else {
            //    alert('Geocode was not successful for the following reason: ' + status);
            //  }
           });
         }
     </script>
     <script async defer
     src="https://maps.googleapis.com/maps/api/js?key=AIzaSyALTmC--e7ho0gW9wMgqeK2NaXybqVRch4&callback=initMap">
     </script>

app/views/admin/restaurants/store_pendding.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%=admin_restaurants_path%>">Quản lý cửa hàng<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
        <li ><a href="<%=admin_restaurants_store_pendding_path%>">Cửa hàng chờ duyệt<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-hourglass"></span></a></li>

      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <!-- <div class="btn-group">
    <a class="btn btn-default " href="<%=admin_restaurants_path%>">Quản lý cửa hàng</a>
    <a href="" class="btn btn-info">Cửa hàng chờ duyệt</a>
  </div> -->
  <h1 class="text-center text-danger margin_bottom_50">Danh sách cửa hàng chờ duyệt</h1>
  <!-- <a href="<%= new_dashboard_restaurant_path%>" class = " btn btn-primary margin_bottom_10">Tạo cửa hàng</a> -->

  <table class="table table-hover table-bordered" >
    <tr style="background: pink">
      <th>STT</th>
      <th>Tên cửa hàng</th>
      <th>Số điện thoại</th>
      <th>Địa chỉ</th>
      <th>Ngày tạo</th>
      <th>Chức năng</th>
    </tr>
    <% @restaurants.each_with_index do |restaurant,index| %>
    <tr class="box-restaurants">
      <td><%= index + 1 + (@page-1)*3  %></td>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.phone %></td>
      <td><%= restaurant.address %>, <%= restaurant.district.name %>, <%=restaurant.district.city.name%></td>
      <td><%= restaurant.created_at.strftime("%H:%M %d/%m/%Y") %></td>
      <td>
        <a href="<%= admin_restaurant_path(restaurant) %>"  class="btn btn-primary">Xem</a>
        <a href="<%= admin_restaurant_path(restaurant) %>" data-method ="patch"  data-confirm="Bạn có muốn duyệt không" class="btn btn-warning">Duyệt</a>
        <a href="<%= admin_restaurant_path(restaurant) %>" data-method ="delete" data-confirm="Bạn có muốn xóa không" class="btn btn-danger" >Xóa</a>
      </td>
    </tr>

    <% end %>
  </table>
  <div class="pagination pull-right">
    <%= will_paginate @restaurants , renderer: BootstrapPagination::Rails %>
  </div>



</div>