config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do

      resources :districts, only: [] do
        collection do
          get :return_districts_by_city_id
        end
      end

      # resources :restaurants, only: [] do
      #   collection do
      #     get :find_restaurants_by_city
      #   end
      # end
      resources :posts, only: [] do
        member do
          post :like
        end

        collection do
          get :more_post
        end

      end
      resources :comments do
        member do
          post :create_reply_comment
          get :replies
          delete :destroy_reply
        end
      end

      resources :carts, only: [] do
        member do
          post :choose_food
          post :increase_quantity
          post :decrease_quantity
          post :cancel_food
          post :cart
        end
      end

      resources :notifications, only: [] do
        collection do
          get :check_notification
        end
      end
      # resources :reviews, only: [] do
      #   member do
      #     delete :destroy_review
      #   end
      # end

    end
  end

  namespace :admin do
    get 'restaurants/store_pendding', to: 'restaurants#store_pendding'
    resources :restaurants do
      collection do
        get :find_restaurant
      end
    end
    resources :users do
      collection do
        get :find_user
      end
    end
    resources :posts do
      collection do
        get :find_post
      end
    end
  end

  namespace :dashboard do
    get 'restaurants/store_pendding', to: 'restaurants#store_pendding'
    resources :restaurants do
      resources :foods do
        collection do
          get :find_food
        end
      end

      resources :staffs do
        collection do
          get :find_staff
        end
      end

      resources :orders, only: [] do
        collection do
          get :orders_pending
          get :orders_shipping
          get :orders_complete
          get :orders_cancel
        end


        member do
          patch :accept_order
          patch :complete_ship
          patch :cancel_order
        end
      end

    end

    resources :orders, only: [] do
      collection do
        get :orders_pending_user
        get :orders_shipping_user
        get :orders_complete_user
        get :orders_cancel_user
      end


      member do
        patch :cancel_order_user
      end
    end

    resources :posts do
      collection do
        get :find_post
      end
    end
  end

  resources :posts do
    collection do
      get :find_post
      get :contact
      post :create_contact
    end

  end
  # resources :comments
  resources :restaurants do

    resources :reviews
    member do
      get :show_foods_drinks
      get :new_cart
      post :cart

    end

    collection do
      get :find_restaurant
      get :find_restaurant_by_address
    end
  end
  resources :users do
    member do
      post :change_password
    end
  end


  get"/login" => "sessions#new", as: :login
  post"/sign" => "sessions#create"
  get"/logout" => "sessions#logout"
  # get "/api/v1/return_districts_by_city_id"  => "api/v1/districts#return_districts_by_city_id"
end

app/models/post.rb
class Post < ApplicationRecord

  validates :user_id, presence: true
  validates :content , presence: true

  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  def index
    @page = 1
    @posts = Post.order('created_at desc').paginate(:page => params[:page], :per_page => 5)
    @page = params[:page].to_i if params[:page].present?
  end

  def find_post
    @page = 1
    title_name = params[:title_name]
    @posts = Post.where("title like ?", "%#{title_name}%").paginate(:page => params[:page], :per_page => 3)
    @page = params[:page].to_i if params[:page].present?
    if @posts.first.nil?
      flash[:error] = "Không tìm thấy bài đăng "
      redirect_to admin_posts_path
    end
  end

  def destroy
    redirect_to posts_path if !@current_user.is_admin?
    @post = Post.find_by_id params[:id]
    if @post.destroy
      flash[:success]= "Bạn vừa xóa bài viết thành công"
      redirect_to admin_posts_path
    else
      render :index
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api::V1
  class PostsController < ApiController
    def like
      @post= Post.find(params[:id])
      like = @post.likes.where(user_id: current_user.id).first
      if like
        like.update isLike: !like.isLike
      else
        like =@post.likes.new user_id: current_user.id, isLike: true
        like.save
      end
      render json:
      {
        success: true,
        data: {
          likes: @post.likes.where(isLike: true).count,
          isLike: like.isLike}
      }
    end

    def more_post
      @page = params[:page]
      @posts = Post.order('created_at desc').paginate(:page => @page, :per_page => 5)
      html = render_to_string(show: 'api/v1/posts/more_post.html.erb', layout: false)
      render json: {
        data: html
      }
    end
  end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < Dashboard::BaseController

  before_action :find_post_by_id, only: [:edit, :update, :destroy]
  def index
    @page = 1
    @posts = @current_user.posts.order('created_at desc').paginate(:page => params[:page], :per_page => 5)
    @page =  params[:page].to_i if params[:page].present?
  end

  def find_post
    @page = 1
    title_name = params[:title_name]
    @posts = @current_user.posts.where("title like ? ", "%#{title_name}%").paginate(:page => params[:page], :per_page =>5)
    @page = params[:page].to_i if params[:page].present?
    if @posts.first.nil?
      flash[:error] = "Không tìm thấy bài đăng"
      redirect_to dashboard_posts_path
    end

  end

  def edit
    # redirect_to posts_path if @post.user_id != @current_user.id
    if !(@post.user_id == @current_user.id || @current_user.is_admin? )
      redirect_to dashboard_post_path
    end
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success]= "Bạn vừa sửa bài viết thành công"
      redirect_to dashboard_posts_path
    else
      render :edit
    end
  end


  def destroy
    # redirect_to posts_path if @post.user_id != @current_user.id
    if !(@post.user_id == @current_user.id || @current_user.is_admin? )
      redirect_to dashboard_posts_path
    end
    if @post.destroy
      flash[:success]= "Bạn vừa xóa bài viết thành công"
      redirect_to dashboard_posts_path
    else
      render :index
    end
  end

  private

  def check_user
      redirect_to login_path if @current_user.nil?
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post_by_id
    @post = Post.find_by_id params[:id]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_user, except: [:index, :show, :contact, :create_contact, :find_post]
  before_action :find_post_by_id, only: [:edit, :update, :show, :destroy, :like]
  def index

    @posts = Post.order('created_at desc').paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def find_post
    @page = 1
    title_name = params[:title_name]
    @posts = Post.where("title like ?", "%#{title_name}%").paginate(:page => params[:page], :per_page => 5)
    @page = params[:page].to_i if params[:page].present?
    if @posts.first.nil?
      flash[:error] = "Không tìm thấy bài đăng "
      redirect_to posts_path
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = @current_user.posts.new post_params
    if @post.save
      flash[:success]= "Bạn vừa đăng bài viết mới thành công"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    # redirect_to posts_path if @post.user_id != @current_user.id
    if !(@post.user_id == @current_user.id || @current_user.is_admin? )
      redirect_to posts_path
    end
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success]= "Bạn vừa sửa bài viết thành công"
      redirect_to dashboard_posts_path
    else
      render :edit
    end
  end

  def show

  end

  def destroy
    # redirect_to posts_path if @post.user_id != @current_user.id
    if !(@post.user_id == @current_user.id || @current_user.is_admin? )
      redirect_to posts_path
    end
    if @post.destroy
      flash[:success]= "Bạn vừa xóa bài viết thành công"
      redirect_to posts_path
    else
      render :index
    end
  end

  def contact

  end

  def create_contact
    name = params[:name]
    email = params[:email]
    subject = params[:subject]
    content = params[:content]
    if @current_user
      user = @current_user.id
    else
      user = "chưa đăng ký"
    end
    if ExampleMailer.contact_email(user ,name, email, subject, content).deliver_now
      flash[:success] = 'Gửi liên hệ thành công'
      redirect_to contact_posts_path
    else
      flash[:error] = 'Gửi liên hệ thất bại'
      render :contact
    end
  end

  # def like
  #   @post= Post.find(params[:id])
  #   like = @post.likes.where(user_id: current_user.id).first
  #   if like
  #     like.update isLike: !like.isLike
  #   else
  #     like =@post.likes.new user_id: current_user.id, isLike: true
  #     like.save
  #   end
  #   render json:
  #   {
  #     success: true,
  #     data: {
  #       likes: @post.likes.where(isLike: true).count,
  #       isLike: like.isLike}
  #   }
  # end

  private

  def check_user
      redirect_to login_path if @current_user.nil?
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post_by_id
    @post = Post.find_by_id params[:id]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/contact.html.erb
<div class="container">


<!-- CONTRACT -->
<section id="contact" class="col-md-12">
    <div class="col-md-8 col-sm-offset-2" >
      <div class="row">
        <div class="contact-heading text-center col-sm-8 col-sm-offset-2">
          <h1 class="margin_bottom_50">Liên hệ</h1>
          <!-- <p>Liên hệ với chúng tôi để biết thêm thông tin.</p> -->
        </div>
      </div>
      <div >
        <div class="row">
          <div class="col-sm-6">
            <form  class="contact-form" action="<%=create_contact_posts_path%>" method="post">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              <div class="row" >
                <div class="col-sm-6">
                  <div class="form-group">
                    <input type="text" name="name" class="form-control" <% if @current_user%> value="<%=@current_user.name%>" <%end%> placeholder="Tên" required="required">
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group">
                    <input type="email" name="email" class="form-control" <% if @current_user%> value="<%=@current_user.email%>" <%end%>  placeholder="Email" required="required">
                  </div>
                </div>
              </div>
              <div class="form-group">
                <input type="text" name="subject" class="form-control" placeholder="Chủ đề" required="required">
              </div>
              <div class="form-group">
                <textarea name="content" id="content" class="form-control" rows="4" placeholder="Nội dung" required="required"></textarea>
              </div>
              <div class="form-group">
                <button type="submit" class="btn btn-primary col-md-12 ">Gửi</button>
              </div>
            </form>
          </div>
          <div class="col-sm-6">
            <div class="contact-info wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
              <p>Liên hệ với chúng tôi để biết thêm thông tin.</p>
              <ul class="contact-address">
                <li> <span> Address:</span>  Ktx DMC 579 - P.Hòa Khánh-Q.Liên Chiểu - TP.Đà Nẵng</li>
                <li><span> Phone:</span> 0989 899 466  </li>
                <li><span> Email:</span><a href="mailto:someone@yoursite.com"> lekhoa2310@gmail.com</a></li>
                <li><span> Website:</span> <a href="#">www.amthuc3mien.com</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<!-- Footer -->
</div>

app/views/posts/edit.erb
<% if @post.errors.any? %>
  <div class="col-md-12 alert alert-danger">
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message%></li>
    <%end%>
  </div>
<% end %>

<div class="container">
  <h1 class="text-center text-danger">Sữa bài viết</h1>
  <fieldtest>
  <%= form_for :post, url: post_path, method: "patch"  do |f| %>
    <div class="col-md-4 col-sm-offset-4">
      <div class="form-group">
        <label for="exampleInputName">Tiêu đề</label>
        <%= f.text_field :title, class: "form-control", placeholder: "Tiêu đề"%>
      </div>
      <div class="form-group">
        <label for="exampleInputName">Nội dung</label>
        <%= f.text_area :content, class: "form-control", placeholder: "Nội dung", required: "required",  size: "24x6"%>
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-primary text-center" name="button">Sửa</button>
        <a class=" text-center btn btn-danger margin_left_10" href="<%= posts_path%>">Hủy</a>
      </div>
    </div>
      <%end%>
      </fieldtest>
  </div>

app/views/posts/find_post.html.erb
<div id="home-page">

<div class="container">
  <div class="col-md-8 col-sm-offset-2">
    <div class="row">
      <div class="col-md-12 row">
        <div class="margin_top_10 form-group col-md-6 row">
          <form class="navbar-form" role="search" action="/posts/find_post" method="get">
          <div class="input-group">
              <input type="text" class="form-control" placeholder="Tên tiêu đề..." name="title_name">
              <div class="input-group-btn">

                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
          </div>
          </form>
        </div>
      </div>
    </div>
  <h1 class="text-center text-danger">Bài đăng tương ứng</h1>
    <% if @current_user %>
      <a href="<%=new_post_path%>"  class="btn btn-info margin_bottom_10" >Đăng bài</a>
    <%else%>
      <button class="btn btn-info margin_bottom_10 return-login">Đăng bài</button>
    <%end%>
    <% @posts.each do |post| %>
      <div class="post-item">
        <% if @current_user %>
          <%if @current_user.id == post.user_id || @current_user.is_admin?%>
            <div class="dropdown option">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              	<i class="glyphicon glyphicon-pencil"></i>
                <!-- glyphicon-th-list -->
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li><a class="dropdown-item" href="#">Xem</a></li>
              <li><a class="dropdown-item" href="<%= edit_post_path(post)%>">Sửa</a></li>
              <li><a class="dropdown-item " href="<%= post_path(post)%> "data-method="delete" data-confirm="Bạn chắc chắn muốn xóa?">Xóa</a></li>
              </div>
            </div>
          <%end%>
        <%end%>
        <h3> <%= image_tag post.user.avatar.url(:avatar), class: " avatar_post" %> <span class="text-primary text-strong"><%= post.user.name%></span> <span href="<%= post_path(post)%>" > <%= post.title %></span></h3>
        <p class="text-muted"> <%= post.created_at.strftime("%H:%M %d/%m/%Y")%></p>
        <div class="margin_bottom_10">
          <%= post.content %>
        </div>

        <%if @current_user%>
          <%like = post.likes.where(user_id: @current_user.id).first%>
          <!-- <button data-target="<%= like_api_v1_post_path(post.id) %>"  data-method ="post" class="btn btn-primary post-like"><%= like.try(:isLike) ? "Không thích" : "Thích"%></button> -->
          <%if like.try(:isLike)%>
            <button data-target="<%= like_api_v1_post_path(post.id) %>"  data-method ="post" class="btn btn-primary post-like"><i class="glyphicon glyphicon-heart"></i> Thích</button>
          <%else%>
            <button data-target="<%= like_api_v1_post_path(post.id) %>"  data-method ="post" class="btn btn-default post-like"><i class="glyphicon glyphicon-heart"></i> Thích</button>
          <%end%>
        <%else%>
          <button class="btn btn-primary return-login"><i class="glyphicon glyphicon-heart"></i> Thích</button>
        <%end%>
        <a href="<%=post_path(post)%>" class="btn btn-success"><i class="glyphicon glyphicon-comment"></i> Bình luận (<%= post.comments.count%>) </a>
        <p class="view-like text-primary">
          <%= post.likes.where(isLike: true).count %> người thích nội dung này
        </p>
      </div>


    <%end %>
      <div class="pagination pull-right">
        <%= will_paginate @restaurants , renderer: BootstrapPagination::Rails %>
      </div>
  </div>

</div>
</div>

app/views/posts/index.html.erb
  <div id="myCarousel" class="carousel slide " data-ride="carousel">

      <div class="carousel-inner" >
        <div class="item active">
          <img src="/assets/slider/monan15.jpg" alt="New York" width="1000" height="700">
          <div class="carousel-caption">
            <p>Ẩm thực 3 miền</p>
            <span>Thoải mái để chọn nhà hàng và món ăn mình muốn.</span>
            <% if @current_user.blank?%>
              <div class="button-index">
                <a class="btn " href="<%=new_user_path%>">Đăng ký</a>
                <a class="btn btn-primary" href="<%=login_path%>">Đăng nhập</a>
              </div>
            <%end%>

          </div>

        </div>

        <div class="item">
          <img src="/assets/slider/monan27.jpg" alt="Chicago" width="1200" height="700">
          <div class="carousel-caption">
            <p>Ẩm thực 3 miền</p>
            <span>Hảy đến với chúng tôi để tận hưởng những điều tuyệt vời nhất.</span>
            <% if @current_user.blank?%>
              <div class="button-index">
                <a class="btn " href="<%=new_user_path%>">Đăng ký</a>
                <a class="btn btn-primary" href="<%=login_path%>">Đăng nhập</a>
              </div>
            <%end%>
          </div>
        </div>

        <div class="item">
          <img src="/assets/slider/monan26.jpg" alt="Los Angeles" width="1200" height="700">
          <div class="carousel-caption">
            <p>Ẩm thực 3 miền</p>
            <span>Hảy nhanh tay đăng ký để tận hưởng ứng dụng tuyệt vời của chúng tôi</span>
            <% if @current_user.blank?%>
              <div class="button-index">
                <a class="btn " href="<%=new_user_path%>">Đăng ký</a>
                <a class="btn btn-primary" href="<%=login_path%>">Đăng nhập</a>
              </div>
            <%end%>
          </div>
        </div>
      </div>
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
  </div>

<div class="container">
<section id="posts">
  <div class="col-md-8 col-sm-offset-2">
    <div class="row">
      <div class="col-md-12 row">
        <div class="margin_top_10 form-group col-md-6 row">
          <form class="navbar-form" role="search" action="/posts/find_post" method="get">
          <div class="input-group">
              <input type="text" class="form-control" placeholder="Tên tiêu đề..." name="title_name">
              <div class="input-group-btn">

                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>  </button>
              </div>
          </div>
          </form>
        </div>
      </div>
    </div>
  <h1 class="text-center text-danger">Danh sách các bài đăng</h1>
    <% if @current_user %>
      <a href="<%=new_post_path%>"  class="btn btn-info margin_bottom_10" >Đăng bài</a>
    <%else%>
      <button class="btn btn-info margin_bottom_10 return-login">Đăng bài</button>
    <%end%>
    <div class="box-posts">
      <% @posts.each do |post| %>
        <div class="post-item">
          <% if @current_user %>
            <%if @current_user.id == post.user_id || @current_user.is_admin?%>
              <div class="dropdown option">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="glyphicon glyphicon-pencil"></i>
                  <!-- glyphicon glyphicon-th-list -->
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li><a class="dropdown-item" href="<%= post_path(post)%>">Xem</a></li>
                <li><a class="dropdown-item" href="<%= edit_post_path(post)%>">Sửa</a></li>
                <li><a class="dropdown-item " href="<%= post_path(post)%> "data-method="delete" data-confirm="Bạn chắc chắn muốn xóa?">Xóa</a></li>
                </div>
              </div>
            <%end%>
          <%end%>
          <h3> <%= image_tag post.user.avatar.url(:big), class: " avatar_post" %> <span class="text-primary text-strong"><%= post.user.name%></span> <span href="<%= post_path(post)%>" > <%= post.title %></span></h3>
          <p class="text-muted"> <%= post.created_at.strftime("at %I:%M%p %d/%m/%Y")%></p>
          <div class="margin_bottom_10">
            <%= post.content %>
          </div>

          <%if @current_user%>
            <%like = post.likes.where(user_id: @current_user.id).first%>
            <!-- <button data-target="<%= like_api_v1_post_path(post.id) %>"  data-method ="post" class="btn btn-primary post-like"><%= like.try(:isLike) ? "Không thích" : "Thích"%></button> -->
            <%if like.try(:isLike)%>
              <button data-target="<%= like_api_v1_post_path(post.id) %>"  data-method ="post" class="btn btn-primary post-like"><i class="glyphicon glyphicon glyphicon-heart"></i> Thích   </button>
            <%else%>
              <button data-target="<%= like_api_v1_post_path(post.id) %>"  data-method ="post" class="btn btn-default post-like"><i class="glyphicon glyphicon glyphicon-heart"></i> Thích</button>
            <%end%>
          <%else%>
            <button class="btn btn-primary return-login"><i class="glyphicon glyphicon-heart"></i> Thích</button>
          <%end%>
          <a href="<%=post_path(post)%>" class="btn btn-success"><i class="glyphicon glyphicon-comment"></i> Bình luận (<%= post.comments.count%>) </a>
          <p class="view-like text-primary">
            <%= post.likes.where(isLike: true).count %> người thích nội dung này
          </p>
        </div>
      <%end %>
    </div>
      <!-- <div class="pagination pull-right " >
        <%= will_paginate @restaurants , renderer: BootstrapPagination::Rails %>
      </div> -->
  </div>
</section>

</div>
<footer class="text-center col-md-12" >
  <a class="up-arrow" href="#myCarousel" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a><br><br>
</footer>

app/views/posts/show.html.erb
<div class="container">
  <div class="col-md-8 col-sm-offset-2 background_content">
    <div class="post-item ">
    <% if @current_user %>
      <%if @current_user.id == @post.user_id%>
        <div class="dropdown option">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <i class="glyphicon glyphicon-pencil "></i>
           <!-- glyphicon glyphicon-th-list -->
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <!-- <li><a class="dropdown-item" href="#">Xem</a></li> -->
          <li><a class="dropdown-item" href="<%= edit_post_path(@post)%>">Sửa</a></li>
          <li><a class="dropdown-item " href="<%= post_path(@post)%> "data-method="delete" data-confirm="Bạn chắc chắn muốn xóa?">Xóa</a></li>
          </div>
        </div>
      <%end%>
    <%end%>
      <h3 class="text-danger"> <%= image_tag @post.user.avatar.url(:big), class: " avatar_post" %> <span class="text-primary text-strong"><%= @post.user.name%>:</span> <%= @post.title %></h3>
    <div class="margin_bottom_10">
      <%= @post.content %>
    </div>

    <div class="">
      <%if @current_user%>
        <%like = @post.likes.where(user_id: @current_user.id).first%>
        <!-- <button data-target="<%= like_api_v1_post_path(@post.id) %>"  data-method ="post" class="btn btn-primary post-like "><%= like.try(:isLike) ? "Không thích" : "Thích"%></button> -->
        <%if like.try(:isLike)%>
          <button data-target="<%= like_api_v1_post_path(@post.id) %>"  data-method ="post" class="btn btn-primary post-like"><i class="glyphicon glyphicon-heart"></i> Thích</button>
        <%else%>
          <button data-target="<%= like_api_v1_post_path(@post.id) %>"  data-method ="post" class="btn btn-default post-like"><i class="glyphicon glyphicon-heart"></i> Thích</button>
        <%end%>
      <%else%>
        <button class="btn btn-primary return-login"><i class="glyphicon glyphicon glyphicon-heart"> </i>  Thích</button>
      <%end%>
    </div>
    <p class="view-like text-primary">
      <%= @post.likes.where(isLike: true).count %> người thích nội dung này
    </p>

    <div class="row">
      <div class="col-md-6 form-comment ">
        <!-- remote để send bằng ajax not submit -->
        <%if @current_user %> <%= image_tag @current_user.avatar.url(:avatar), class: " avatar_picture" %> <%end%>
        <%= form_for([:api, :v1, Comment.new], remote: true)  do |f| %>
          <fieldtest>
          <%= f.text_area :content , class: "form-control  " , required: "required", placeholder: "Viết bình luận..."%>
          <%= f.hidden_field :post_id, as: :hidden, value: @post.id %>
          <%= f.hidden_field :current_user, as: :hidden, value: @current_user %>
          <!-- <%if @current_user%>
            <button type="button"  class="btn btn-primary post-comment" >Bình luận</button>
          <%else%>
            <button type="button"  class="btn btn-primary return-login" >Bình luận</button>
          <%end%> -->
          </fieldtest>
        <% end %>

      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <ul class="list-comment list-unstyled ">
          <% @post.comments.each do |comment| %>
          <div class="comment-item row ">
            <li class="box-comment  col-md-12 margin_top_20 row">
                <div class="col-md-9">
                  <span class="text-primary text-strong"> <%= image_tag comment.user.avatar.url(:avatar), class: " avatar_picture" %> <%= comment.user.name %>:</span> <%= comment.content %>
                  <div class=" col-md-12  box-replies">
                    <a class="reply-comment" data-target="<%=comment.id%>" >Hiện <span class="count-replies"> <%= reply = Comment.where(comment_id: comment.id).count%> </span>trả lời</a>
                    <div class="replies"></div>
                  </div>
                </div>
                <div class="col-md-3">
                <% if @current_user%>
                  <%if @current_user.id == comment.user.id%>
                    <span data-target="<%= comment.id %>" class="text-danger delete-comment"  >x</span>
                  <%end%>
                <%end%>
                </div>
            </li>
          </div>
          <% end%>
        </ul>
      </div>
    </div>


    </div>
  </div>
</div>